Funnel state -> states-dev
GreenBlitz/2024-Offseason-robot pull request #12
Opened 2024-10-02 11:17 UTC by drorta

2024-10-02 14:13 UTC, hillelv approved these changes, later dismissed

2024-10-03 12:06 UTC, Nitay4 submitted a review, later dismissed
noicee

2024-10-03 14:40 UTC, Yotam7 commented on src/main/java/frc/robot/subsystems/funnel/factory/RealFunnelConstants.java
> +		sparkMAXWrapper.setSmartCurrentLimit(30);
magic number

2024-10-04 10:18 UTC, Yotam7 approved these changes, later dismissed

2024-10-04 15:01 UTC, YHerm approved these changes, later dismissed

2024-10-04 15:11 UTC, bossyshrimp68 requested changes
This isnt updated to funnel

2024-10-04 15:11 UTC, bossyshrimp68 commented on src/main/java/frc/robot/Robot.java
>  		this.superstructure = new Superstructure(this);
Add a space

2024-10-04 15:11 UTC, bossyshrimp68 commented on src/main/java/frc/robot/subsystems/funnel/FunnelState.java
> +	NOTE_TO_SHOOTER(0.1),
No outtake? And orginize this

2024-10-04 15:11 UTC, bossyshrimp68 commented on src/main/java/frc/robot/subsystems/funnel/factory/RealFunnelConstants.java
> +	private final static double DEBOUNCE_TIME_SECONDS = 0.05;
Spaces

2024-10-04 15:11 UTC, bossyshrimp68 commented on src/main/java/frc/robot/subsystems/funnel/factory/RealFunnelConstants.java
> +		sparkMAXWrapper.getReverseLimitSwitch(REVERSE_LIMIT_SWITCH_TYPE).enableLimitSwitch(false);
Const

2024-10-04 16:49 UTC, hillelv commented on src/main/java/frc/robot/subsystems/funnel/FunnelStateHandler.java
> +		}
you don't really need this

2024-10-04 16:49 UTC, hillelv commented on src/main/java/frc/robot/subsystems/funnel/FunnelStateHandler.java
consider moving this to the commands builder

2024-10-04 16:49 UTC, hillelv commented on src/main/java/frc/robot/subsystems/funnel/FunnelStateHandler.java
you don't have stopping conditions, the funnel will run until a different state is set, not regarding the note or the beambreakers

2024-10-04 17:45 UTC, closed without merging