Flywheel states -> Flywheel
GreenBlitz/2024-Offseason-robot pull request #18
Opened 2024-10-03 15:21 UTC by Nitay4

2024-10-03 15:25 UTC, YHerm commented on src/main/java/frc/robot/subsystems/flywheel/FlywheelState.java
> +	Rotation2d velocity;
final

2024-10-03 15:26 UTC, YHerm commented on src/main/java/frc/robot/subsystems/flywheel/FlywheelState.java
> +	public Rotation2d getPower() {
```suggestion
	public Rotation2d getVelocity() {
```

2024-10-03 15:26 UTC, greenblitz4590 commented on src/main/java/frc/robot/subsystems/flywheel/FlywheelState.java
> +	public Rotation2d getPower() {
get velocity

2024-10-03 15:26 UTC, YHerm commented on src/main/java/frc/robot/subsystems/flywheel/FlywheelStateHandler.java
> +	}
add if velocity 0 return stop command

2024-10-03 15:26 UTC, greenblitz4590 commented on src/main/java/frc/robot/subsystems/flywheel/FlywheelStateHandler.java
> +
remvoe one line space

2024-10-03 15:27 UTC, greenblitz4590 requested changes
remove things that souldnt be here

2024-10-03 15:29 UTC, bossyshrimp68 requested changes

2024-10-03 15:29 UTC, bossyshrimp68 commented on \
> +# Please enter a commit message to explain why this merge is necessary,
What is this

2024-10-03 20:51 UTC, drorta approved these changes

2024-10-04 08:42 UTC, drorta approved these changes
nice! also do me a cr on swerve superstructure

2024-10-04 08:45 UTC, YHerm commented on src/main/java/frc/robot/subsystems/flywheel/FlywheelStateHandler.java
> +	public FlywheelStateHandler(Robot robot) {
```suggestion
	public FlywheelStateHandler(Flywheel flywheel) {
```

2024-10-04 09:22 UTC, Yotam7 approved these changes

2024-10-04 16:55 UTC, hillelv reviewed
add flywheel to the superstructure

2024-10-05 15:58 UTC, hillelv commented on src/main/java/frc/robot/subsystems/flywheel/FlywheelState.java
> +	SHOOTER_OUTTAKE(Rotation2d.fromRotations(30)),
erm, what the sigma?

2024-10-05 15:58 UTC, hillelv commented on src/main/java/frc/robot/subsystems/flywheel/FlywheelStateHandler.java
why do you have this if you don't use it

2024-10-05 15:58 UTC, hillelv commented on src/main/java/frc/robot/subsystems/flywheel/FlywheelState.java
> +	SHOOTER_OUTTAKE(Rotation2d.fromRotations(30)),
why does outtake make it go a bit slower

2024-10-06 16:53 UTC, Yotam7 approved these changes

2024-10-06 17:34 UTC, hillelv approved these changes

2024-10-08 02:40 UTC, merged