Funnel -> core
GreenBlitz/2024-Offseason-robot pull request #2
Opened 2024-09-30 16:08 UTC by drorta

2024-09-30 16:20 UTC, YoniKiriaty commented on src/main/java/frc/robot/subsystems/funnel/Funnel.java
> +		return (getPosition().getRotations() - position.getRotations() <= 5);
no paranthesseseses

2024-09-30 17:15 UTC, hillelv requested changes

2024-09-30 17:15 UTC, hillelv commented on src/main/java/frc/robot/subsystems/funnel/FunnelStuff.java
IRequest?

2024-09-30 17:15 UTC, hillelv commented on src/main/java/frc/robot/subsystems/funnel/factory/RealFunnelConstants.java
> +		SparkMaxDoubleSignal voltageSignal = new SparkMaxDoubleSignal("voltage", voltage);
one line

2024-10-01 03:34 UTC, drorta commented on src/main/java/frc/robot/subsystems/funnel/FunnelStuff.java
why?

2024-10-01 03:35 UTC, drorta commented on src/main/java/frc/robot/subsystems/funnel/factory/RealFunnelConstants.java
> +		SparkMaxDoubleSignal voltageSignal = new SparkMaxDoubleSignal("voltage", voltage);
again, why?

2024-10-01 11:17 UTC, greenblitz4590 requested changes

2024-10-01 11:17 UTC, greenblitz4590 commented on src/main/java/frc/robot/subsystems/funnel/Funnel.java
> +	public boolean isObjectInShooter() {
isNoteinShooter?

2024-10-01 11:17 UTC, greenblitz4590 commented on src/main/java/frc/robot/subsystems/funnel/Funnel.java
> +	public void update() {
rename to updateSignls or update inputs

2024-10-01 11:17 UTC, greenblitz4590 commented on src/main/java/frc/robot/subsystems/funnel/Funnel.java
> +		Logger.recordOutput(funnelStuff.logPath() + "IsObjectInShooter", isObjectInShooter());
same here

2024-10-01 13:12 UTC, hillelv commented on src/main/java/frc/robot/subsystems/funnel/factory/RealFunnelConstants.java
> +		SparkMaxDoubleSignal voltageSignal = new SparkMaxDoubleSignal("voltage", voltage);
we will merge a function for this in the template

2024-10-01 15:10 UTC, drorta commented on src/main/java/frc/robot/subsystems/funnel/factory/RealFunnelConstants.java
> +		SparkMaxDoubleSignal voltageSignal = new SparkMaxDoubleSignal("voltage", voltage);
wdym?

2024-10-01 17:44 UTC, YHerm commented on src/main/java/frc/robot/constants/IDs.java
> +		public static final SparkMaxDeviceID FUNNEL = new SparkMaxDeviceID(1, CANSparkLowLevel.MotorType.kBrushless);
sapce above and below

2024-10-01 17:45 UTC, YHerm commented on src/main/java/frc/robot/subsystems/funnel/FunnelCommandsBuilder.java
> +		return new InstantCommand(funnel::stop, funnel).withName("Stop funnel");
run command

2024-10-01 17:53 UTC, drorta commented on src/main/java/frc/robot/subsystems/funnel/FunnelCommandsBuilder.java
> +		return new InstantCommand(funnel::stop, funnel).withName("Stop funnel");
wdym?

2024-10-01 18:58 UTC, Nitay4 requested changes

2024-10-01 18:58 UTC, Nitay4 commented on src/main/java/frc/robot/subsystems/funnel/Funnel.java
> +	private final DigitalInputInputsAutoLogged ampDigitalInputInputs;
maby put them in stuff

2024-10-01 19:01 UTC, drorta commented on src/main/java/frc/robot/subsystems/funnel/Funnel.java
> +	private final DigitalInputInputsAutoLogged ampDigitalInputInputs;
already in stuff, and easier this way

2024-10-01 19:38 UTC, YHerm reviewed
u have conflicts

2024-10-01 20:54 UTC, closed without merging