Swerve Superstructure -> states-dev
GreenBlitz/2024-Offseason-robot pull request #20
Opened 2024-10-03 20:25 UTC by drorta

2024-10-03 20:46 UTC, YHerm commented on src/main/java/frc/robot/Robot.java
> +		);
first thing (put above)

2024-10-03 20:46 UTC, YHerm commented on src/main/java/frc/robot/Robot.java
> +	private final Swerve swerve;
above!

2024-10-03 20:46 UTC, YHerm commented on src/main/java/frc/robot/Robot.java
> +	}
above superstructure

2024-10-03 20:48 UTC, YHerm commented on src/main/java/frc/robot/Robot.java
add in joystickbindings first joystick buttons for swerve
(reset heading and drive)

2024-10-03 20:50 UTC, drorta commented on src/main/java/frc/robot/Robot.java
wdym drive

2024-10-04 09:14 UTC, Nitay4 submitted a review, later dismissed

2024-10-04 09:16 UTC, YHerm approved these changes, later dismissed
Make sure tot test it

2024-10-04 09:48 UTC, Yotam7 approved these changes, later dismissed

2024-10-04 15:05 UTC, bossyshrimp68 requested changes

2024-10-04 15:05 UTC, bossyshrimp68 commented on src/main/java/frc/robot/constants/IDs.java
> +		public static final Phoenix6DeviceID FRONT_LEFT_STEER_MOTOR = new Phoenix6DeviceID(0, BusChain.CANIVORE);
No need for "MOTOR" in any of them

2024-10-04 15:05 UTC, bossyshrimp68 commented on src/main/java/frc/robot/constants/IDs.java
> +	public static final Phoenix6DeviceID PIGEON_2_DEVICE_ID = new Phoenix6DeviceID(0, BusChain.CANIVORE);
No need for "DEVICE_ID" its clear

2024-10-04 15:05 UTC, bossyshrimp68 commented on src/main/java/frc/robot/subsystems/swerve/factories/modules/constants/RealModuleConstants.java
> +	private static final double WHEEL_DIAMETER_METERS = 0.048359 * 2;
Space

2024-10-04 15:05 UTC, bossyshrimp68 commented on src/main/java/frc/robot/subsystems/swerve/factories/swerveconstants/RealSwerveConstants.java
> +public class RealSwerveConstants {
I think its nic3r with spaces and souble spaces

2024-10-04 15:32 UTC, merged