IntakeStates ➝ subsystems-dev
GreenBlitz/2024-Offseason-robot pull request #26
Opened 2024-10-08 12:02 UTC by maya1414

2024-10-08 12:08 UTC, hillelv reviewed
move base branch to states-dev and add the handler to the superstructure

2024-10-08 12:23 UTC, drorta commented on src/main/java/frc/robot/subsystems/intake/IntakeStates.java
> +	SHOOTER_TO_ELEVATOR(0);
elevator to shooter

2024-10-08 16:41 UTC, Yotam7 commented on src/main/java/frc/robot/subsystems/intake/roller/IntakeStates.java
> +	ELEVATOR_TO_SHOOTER(0);
make `STOP` state last
```suggestion
	ELEVATOR_TO_SHOOTER(0),
	STOP(0);
```

2024-10-08 16:46 UTC, Yotam7 commented on src/main/java/frc/robot/subsystems/intake/roller/IntakeStates.java
> +	ELEVATOR_TO_SHOOTER(0);
change order of `IntakeStates` to be more inline with what happens in games
```suggestion
	INTAKE(0),
	NOTE_TO_SHOOTER(0),
	ELEVATOR_TO_SHOOTER(0),
	STOP(0);
```

2024-10-08 16:52 UTC, hillelv commented on src/main/java/frc/robot/subsystems/intake/roller/IntakeStates.java
> +	ELEVATOR_TO_SHOOTER(0);
shooter to elevator

2024-10-08 16:52 UTC, hillelv commented on src/main/java/frc/robot/subsystems/intake/roller/IntakeStates.java
> +public enum IntakeStates {
add outtake state

2024-10-08 18:18 UTC, YHerm commented on src/main/java/frc/robot/superstructure/Superstructure.java
> +			intakeStatesHandler.setState(IntakeStates.STOP)
should do outtake

2024-10-09 13:27 UTC, Yotam7 approved these changes, later dismissed

2024-10-09 13:28 UTC, YoniKiriaty submitted a review, later dismissed

2024-10-09 14:02 UTC, YoniKiriaty submitted a review, later dismissed

2024-10-09 14:08 UTC, YHerm submitted a review, later dismissed

2024-10-09 14:12 UTC, Yotam7 submitted a review, later dismissed

2024-10-09 14:14 UTC, bossyshrimp68 requested changes

2024-10-09 14:14 UTC, bossyshrimp68 commented on src/main/java/frc/robot/subsystems/intake/roller/Calibrations
> +6. STOP power
Why do you need to calibrate stop power..?

2024-10-09 14:17 UTC, bossyshrimp68 approved these changes

2024-10-09 14:18 UTC, Yotam7 approved these changes

2024-10-09 14:19 UTC, YHerm approved these changes

2024-10-09 14:19 UTC, YoniKiriaty approved these changes

2024-10-09 14:21 UTC, drorta approved these changes

2024-10-09 14:21 UTC, hillelv approved these changes

2024-10-09 14:22 UTC, merged