Elevator roller states -> subsystems-dev
GreenBlitz/2024-Offseason-robot pull request #27
Opened 2024-10-08 17:18 UTC by Yotam7

2024-10-08 18:19 UTC, YHerm commented on src/main/java/frc/robot/subsystems/elevatorRoller/ElevatorRollerState.java
> +public enum ElevatorRollerState {
u probably will want one that goes reverse

2024-10-08 18:20 UTC, YHerm commented on src/main/java/frc/robot/subsystems/elevatorRoller/ElevatorRollerState.java
> +	INTAKE_TO_ELEVATOR_ROLLER(0),
```suggestion
	TRANSFER_TO_ELEVATOR(0),
```

2024-10-08 18:20 UTC, YHerm requested changes
uupdtae with subsystems-dev

2024-10-09 13:11 UTC, drorta approved these changes, later dismissed

2024-10-09 13:27 UTC, maya1414 submitted a review, later dismissed

2024-10-09 14:05 UTC, greenblitz4590 commented on src/main/java/frc/robot/superstructure/Superstructure.java
> +			elevatorRollerStateHandler.setState(ElevatorRollerState.STOP),
to elevatro

2024-10-09 14:05 UTC, greenblitz4590 commented on src/main/java/frc/robot/superstructure/Superstructure.java
> +			elevatorRollerStateHandler.setState(ElevatorRollerState.STOP),
from elevator

2024-10-09 14:07 UTC, greenblitz4590 commented on src/main/java/frc/robot/superstructure/Superstructure.java
> +			elevatorRollerStateHandler.setState(ElevatorRollerState.STOP),
reverse, or from elevator

2024-10-09 14:14 UTC, maya1414 submitted a review, later dismissed

2024-10-09 14:28 UTC, YHerm commented on src/main/java/frc/robot/superstructure/Superstructure.java
> +			);
tab less

2024-10-09 14:36 UTC, maya1414 approved these changes, later dismissed

2024-10-09 14:36 UTC, drorta approved these changes, later dismissed

2024-10-09 14:50 UTC, hillelv submitted a review, later dismissed

2024-10-09 14:52 UTC, YHerm submitted a review, later dismissed

2024-10-09 14:56 UTC, bossyshrimp68 submitted a review, later dismissed

2024-10-09 14:56 UTC, bossyshrimp68 commented on src/main/java/frc/robot/subsystems/elevatorRoller/calibarations
> +4. What power should be for INTAKE_TO_ELEVATOR_ROLLER and AMP
"Power for ..." will do

2024-10-09 14:59 UTC, maya1414 approved these changes

2024-10-09 15:05 UTC, merged